In [3]:
dict(range(10))

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [4]:
import numpy as np

a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
#slicing
#start:end:step
a[1:8:3]

array([10, 40, 70])

In [7]:
a[a%2==0]
b = a.copy()

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
a.groupby('column')["Tb"].mean()

In [ ]:
df['age'] = df['age'].astype('int')

In [ ]:
df['age'].fillna(df['age'].mean(),inplace = True)

In [3]:
##based on IQR to remove outliers
from feature_engine.outliers import ArbitaryOutlierCapper
cap = ArbitaryOutlierCapper(max_capping_dict = {'marks':52},min_capping_dict = {'marks':10})
cap.fit_transform(df[["marks"]])

ModuleNotFoundError: No module named 'feature_engine'

In [ ]:
##based on IQR to remove outliers
from feature_engine.outliers import Winsorizer
cap = Winsorizer(capping_method = 'iqr',tail = 'both', fold = 1.5)
cap.fit_transform(df[["marks"]])

In [ ]:
print(win.left_tail_caps_,win.right_tail_caps_)

DATA Wrangling

In [4]:
## to turn our skewed data to normal we can use root for right which is called root transformation
df['sqr_fare'] = df['sqr_fare']**1/4
df['sqr_fare'].skew()

NameError: name 'df' is not defined

In [ ]:
## to turn our skewed data to normal we can use log for left which is called logarithmic transformation
df['sqr_fare'] = np.log(df['sqr_fare']+0.01)
df['sqr_fare'].skew()

In [ ]:
## reciprocal Transformation
df['sqr_fare'] = 1/(df['sqr_fare']+0.01)
df['sqr_fare'].skew()

In [ ]:
##boxcox
from scipy import stats
df['fr'],param=stats.boxcox(data.fare+0.01)
print(param)
df.fr.skew()

Feature scaling
scaling so that the all values are in range
standarization
normalization

Standardisation - centering mean to 0 and std to 1


In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df['fr'] = sc.fit_transform(df['fr'])

## this is same as using x-mean/std

NameError: name 'df' is not defined

In [6]:
##min_max scaling
##x-xmin/xmax-xmin
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
df['fr'] = sc.fit_transform(df['fr'])

## Discretization

In [ ]:
continuous variables into discrete variables by placing values in intervals or bins
handles outliers


In [ ]:
intervals = [0,12,19,25]
categories = ['n1','n2','n3','n4']
df['cats'] = pd.cut(df['age'],bins=intervals,labels=categories)


Encoding

In [ ]:
#label encoder
labelencoder() and fit_transform

In [ ]:
ordinal encoding for converting to numeric as per given order

oe = OrdinalEncoder(categories=[['small','medium','high']])

In [ ]:
Feature mapping

df['ffr'].map({'small':0,'med':1,'high':2})

In [ ]:
OneHotEncoder()
pd.get_dummies